

name: sms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    
    - uses: actions/checkout@v3
    - name: Set up JDK 19.0.1
      uses: actions/setup-java@v3
      with:
        java-version: '19.0.1'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file


    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: roshanadi
          password: dckr_pat_YU9W4wnO1iTAFDTyU2hRe5GWLr0
          
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
          context: .
          push: true
          tags: roshanadi/chatsppspringboot:lates
